spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpa_exam
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: create #create(수정되면서 가동), update(엔티티 수정안됨, 데이터지워지면 안될 때 사용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true